project_id = "nohatbgbowlnfizrqtap"

[functions.mercadopago-create-preference]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.shipping-calculate]
verify_jwt = false

[functions.send-production-email]
verify_jwt = false

[functions.generate-blog-cover]
verify_jwt = false
